create table employees (
	id serial primary key,
	employee_name varchar(50) not null
);
insert into employees (employee_name)
values ('Belle'),
	 	('Melani'),
		('Luisa'),
 		('Elizabeth'),
 		('Violette'),
 		('Nathalia'),
 		('Yasmin'),
		('Elina'),
 		('Queen'),
		('Ayleen'),
 		('Jillian'),
		('Brittany'),
		('Paola'),
		('Carolyn'),
 		('Loretta'),
 		('Drew'),
 		('Dalary'),
 		('Nataly'),
 		('Paloma'),
 		('Veda'),
 		('Raya'),
 		('Whitney'),
		('Flora'),
		('Samira'),
		('Zoya'),
 		('Elza'),
 		('Deborah'),
 		('Ayla'),
 		('Valery'),
		('Robin'),
		('Ellison'),
		('Barbara'),
		('Leanna'),
		('Denver'),
		('Violeta'),
 		('Frida'),
 		('Amaris'),
 		('Karter'),
		('Leo'),
		('Scout'),
		('Aliya'),
		('August'),
		('Denis'),
		('Theodor'),
		('Hunter'),
 		('Livia'),
		('Viena'),
 		('Tiffany'),
 		('Greta'),
		('Harry'),
		('Alex'),
 		('Bred'),
		('Rayan'),
 		('Dexter'),
 		('Roza'),
 		('Ohara'),
		('Ezra'),
		('Jolly'),
 		('Lara'),
		('Kevin'),
		('Karla'),
		('Lilian'),
		('Lara'),
		('Christina'),
		('Timur'),
		('Kate'),
		('Daniel'),
		('Leyla'),
		('Gloria'),
		('Rustam');
select * from employees;

create table salary(
	id serial primary key,
	monthly_salary int not null);
insert into salary(monthly_salary)
values (1000),
 		(1100),
		(1200),
		(1300),
		(1400),
		(1500),
		(1600),
		(1700),
 		(1800),
		(1900),
		(2000),
		(2100),
		(2200),
		(2300),
		(2400),
		(2500);		
select * from salary;


create table employee_salary(
	id serial primary key,
	employee_id int not null unique,
	salary_id int not null
	);
insert into employee_salary (employee_id, salary_id)
values (35, 15),
		(23, 14),
		(30, 5),
		(4, 15),
		(8, 9),
		(64, 11),
		(15, 14),
		(28, 12),
		(17, 15),
		(10, 5),
		(14, 8),
		(12, 9),
		(33, 11),
		(24, 13),
		(60, 7),
		(16, 2),
		(7, 9),
		(51, 6),
		(19, 11),
		(20, 11),
		(31, 12),
		(25, 7),
		(57, 15),
		(9, 5),
		(46, 8),
		(32, 9),
		(41, 11),
		(3, 6),
		(29, 5),
		(1, 15),
		(79, 9),
		(75, 11),
		(73, 2),
		(88, 9),
		(92, 3),
 		(81, 2),
		(96, 11),
		(86, 2),
		(91, 9),
		(84, 3);
select * from employee_salary;


create table roles(
	id serial primary key,
	role_name int not null unique
	);

alter table roles
alter column role_name type varchar(30)
using role_name::varchar(30);
insert into roles (role_name)
values ('Junior Python developer'),
		('Middle Python developer'),
		('Senior Python developer'),
		('Junior Java developer'),
		('Middle Java developer'),
		('Senior Java developer'),
		('Junior JavaScript developer'),
		('Middle JavaScript developer'),
		('Senior JavaScript developer'),
		('Junior Manual QA engineer'),
		('Middle Manual QA engineer'),
		('Senior Manual QA engineer'),
		('Project Manager'),
		('Designer'),
		('HR'),
		('CEO'),
		('Sales manager'),
		('Junior Automation QA engineer'),
		('Middle Automation QA engineer'),
		('Senior Automation QA engineer');
select * from roles;


create table roles_employee(
	id serial primary key,
	employee_id int not null unique,
	role_id int not null,
	foreign key (employee_id)
	references employees (id),
	foreign key (role_id)
	references roles (id)
);
insert into roles_employee (employee_id, role_id)
values(45, 15),
		(65, 3),
		(22, 1),
		(13, 8),
		(12, 2),
		(2, 14),
		(16, 4),
		(70, 11),
		(4, 5),
		(62, 13),
		(15, 7),
		(53, 12),
		(21, 9),
		(34, 10),
		(38, 6),
		(40, 15),
		(44, 3),
		(57, 1),
		(59, 8),
		(3, 2),
		(69, 14),
		(28, 4),
		(1, 11),
		(55, 10),
		(26, 15),
		(8, 3),
		(10, 1),
		(20, 8),
		(39, 2),
		(7, 9),
		(19, 6),
		(24, 15),
		(35, 3),
		(42, 1),
		(48, 8),
		(50, 2),
		(63, 14),
		(68, 11),
		(32, 10),
		(11, 15);
select * from roles_employee;

